"""Exact structural audit for the dual-register comparator hypothesis.

The labels below are one concrete satisfying assignment for

    f = (b == c) and (lvl <= m) xor ((not b) and c and (m >= 6)).

They are intentionally stored explicitly rather than regenerated by an
optimizer, so the artifact is reproducible and reviewable.
"""

import json
from pathlib import Path

from search import logo


# One exact satisfying assignment, indexed by the six-bit input value.
X_C = [0, 0] + [1] * 25 + [0] * 23 + [1] * 11 + [0] * 3
X_LVL = ([7, 7] + [3] * 25 + [6] * 5 + [5, 4, 3, 3, 2, 2]
         + [1] * 5 + [2, 2, 3, 3, 4, 5, 6, 6, 5, 5]
         + [4] * 5 + [5, 5, 6, 6, 7, 7])
Y_B = ([0] + [1] * 10 + [0] * 17 + [1] * 11 + [0] * 5
        + [1] * 19 + [0] * 1)
Y_M = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 4, 4,
       5, 5, 5, 5, 5, 4, 4, 3, 3, 2, 1, 0, 3, 3, 3, 3, 3, 3,
       4, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 4, 3, 3, 3, 3, 3,
       3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


def formula(x, y):
    b, m = Y_B[y], Y_M[y]
    c, level = X_C[x], X_LVL[x]
    return ((b == c) and (level <= m)) ^ ((not b) and c and (m >= 6))


def alternatives(values, side):
    """Return alternate labels preserving the fixed opposite register.

    This is a diagnostic notion of don't-care freedom, not a claim that the
    alternatives are globally interchangeable.
    """
    out = []
    for i, value in enumerate(values):
        if side == "x":
            current = (X_C[i], X_LVL[i])
            choices = [(c, level) for c in (0, 1) for level in range(8)]
        else:
            current = (Y_B[i], Y_M[i])
            choices = [(b, m) for b in (0, 1) for m in range(8)]
        # A label is locally free if replacing it leaves the full truth table
        # unchanged while all labels on the other register remain fixed.
        keep = []
        for candidate in choices:
            if candidate == current:
                continue
            if side == "x":
                old = X_C[i], X_LVL[i]
                X_C[i], X_LVL[i] = candidate
                ok = all(formula(x, y) == bool(logo(x, y))
                         for x in range(64) for y in range(64))
                X_C[i], X_LVL[i] = old
            else:
                old = Y_B[i], Y_M[i]
                Y_B[i], Y_M[i] = candidate
                ok = all(formula(x, y) == bool(logo(x, y))
                         for x in range(64) for y in range(64))
                Y_B[i], Y_M[i] = old
            if ok:
                keep.append({"b": candidate[0], "m": candidate[1]} if side == "y"
                            else {"c": candidate[0], "lvl": candidate[1]})
        out.append(keep)
    return out


def build_report():
    assert len(X_C) == len(X_LVL) == len(Y_B) == len(Y_M) == 64
    mismatches = [{"x": x, "y": y, "expected": int(logo(x, y)),
                   "actual": int(formula(x, y))}
                  for y in range(64) for x in range(64)
                  if formula(x, y) != bool(logo(x, y))]
    x_alternatives = alternatives(X_C, "x")
    y_alternatives = alternatives(Y_B, "y")
    return {
        "formula": "(b == c) AND (lvl <= m) XOR ((NOT b) AND c AND (m >= 6))",
        "mismatches": len(mismatches),
        "counterexamples": mismatches,
        "x": [{"x": x, "c": X_C[x], "lvl": X_LVL[x],
               "dont_care_alternatives": x_alternatives[x]}
              for x in range(64)],
        "y": [{"y": y, "b": Y_B[y], "m": Y_M[y],
               "dont_care_alternatives": y_alternatives[y]}
              for y in range(64)],
        "source_predicate": "src/search.py::logo",
        "status": "exact structural identity; no circuit claim",
    }


if __name__ == "__main__":
    report = build_report()
    path = Path("artifacts/comparator_oracle/structure.json")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps({"mismatches": report["mismatches"], "path": str(path)}, indent=2))
