"""Extend the wire-labelled beam to 128 phase terms; keep <=64 behavior identical."""
from pathlib import Path

HERE = Path(__file__).resolve().parent
s = (HERE / 'kbeam_wirehash.c').read_text()
s = '// Generated by mk_kbeam128.py; phase bitsets span 128 terms.\n' + s
s = s.replace('uint64_t done;', '__uint128_t done;')
s = s.replace('term[64]', 'term[128]')
s = s.replace('static inline int popc64(uint64_t x){ return __builtin_popcountll(x); }',
              'static inline int popc64(__uint128_t x){ return __builtin_popcountll((uint64_t)x) + __builtin_popcountll((uint64_t)(x>>64)); }')
s = s.replace('uint64_t ALLDONE', '__uint128_t ALLDONE')
s = s.replace('uint64_t LATESET', '__uint128_t LATESET')
s = s.replace('uint64_t reach', '__uint128_t reach')
s = s.replace('1ull<<', '((__uint128_t)1)<<')
s = s.replace('(P==64)?~0ull:', '(P==128)?~(__uint128_t)0:')
s = s.replace('uint64_t h=s->done*0x9E3779B97F4A7C15ull;',
              'uint64_t h=(uint64_t)s->done*0x9E3779B97F4A7C15ull ^ (uint64_t)(s->done>>64)*0xD6E8FEB86659FD93ull;')
s = s.replace('if(scanf("%d",&P)!=1) return 1;',
              'if(scanf("%d",&P)!=1 || P<1 || P>128) return 1;')
(HERE / 'kbeam128.c').write_text(s)
print(HERE / 'kbeam128.c')
